[build]
  command = "npm install"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/api/participants/:id"
  to = "/.netlify/functions/delete-participant"
  status = 200
  force = true

[[redirects]]
  from = "/api/participants"
  to = "/.netlify/functions/participants"
  status = 200

[[redirects]]
  from = "/api/check-email/:email"
  to = "/.netlify/functions/check-email/:email"
  status = 200

[[redirects]]
  from = "/api/admin/participants"
  to = "/.netlify/functions/admin-participants"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

